In [9]:
def isnum(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
li = ["10","20","30","a","b"]
a=map(isnum,li)
list(a)

[True, True, True, False]

In [11]:
a = filter(isnum,li)
list(a)

['10', '20', '30']

### ***lambda***

In [15]:
def sum1(a,b):
    c = a+b
    return c
sum1(4,19)

23

In [14]:
a = lambda x,y: x+y
a(37,38)

75

In [16]:
def squareof(a):
    b=a*a
    return b
squareof(5)

25

In [17]:
a=lambda a:a*a
a(19)

361

### ***list comprehension***

In [19]:
a = int(input("enter a : "))
for i in range(0,a+1):
    print(i**2)

enter a : 5
0
1
4
9
16
25


In [20]:
a = [i**2 for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [1]:
def factorialof(n):
    fact =1
    for i in range(1,n+1):
        fact=fact*i
    print("the factorial of",n,"is",fact)

In [2]:
factorialof(5)

the factorial of 5 is 120


In [28]:
a = int(input("enter a: "))
b=1
for i in range(1,a+1):
    b*=i
print(b) 

enter a: 19
121645100408832000


In [1]:
import math
s = [math.factorial(i) for i in range(1,10)]
s


[1, 2, 6, 24, 120, 720, 5040, 40320, 362880]

### ***file handling***

* performing operations on a file is called file handling,
* entering some data to a file is called write to a file.
* retrieving data from a file is called reading from a file.
* we can perform append,delete operations on files.

In [21]:
def writetoafile(filename,data):
    with open(filename,"w") as t:
        t.write(data)
    return
filename ="data.txt"
writetoafile(filename,"anu\nmona\nteju3g\nteju4g\n")
 

In [22]:
def readfromafile(filename):
    with open(filename,"r") as t:
        td=t.read()
        t.close()
    return td
readfromafile("data.txt")
  

'anu\nmona\nteju3g\nteju4g\n'

In [23]:
def readfromafile(filename):
    with open(filename,"r") as t:
        td=t.read()
        t.close()
    return td
filename="data.txt"
readfromafile("data.txt")
def printlines(filename):
    with open (filename,"r") as t:
        for line in t:
            print(line,end = "")
    return
printlines(filename)
#print(readfromafile(filename))

anu
mona
teju3g
teju4g


In [28]:
def readfromafile(filename):
    with open(filename,"r") as f:
        fd=f.read()
        f.close()
    return fd
filename="teju.txt"
readfromafile("teju.txt")
def printlines(filename):
    with open (filename,"r") as f:
        for line in f:
            print(line,end = "")
    return
printlines(filename)
#print(readfromafile(filename))

def subtacttwonums(a,b):
    a=int(input())
    b=int(input())
        c=a-b
    return c
subtracttwonums(5,3)


In [32]:
def appendtofile(filename,data):
    with open(filename,"a")as f:
        for line in data:
            f.write("\n"+line)
        return
data=["priya","kamalulla","shalim"]
filename = "data.txt"
appendtofile(filename,data)

## ***Numpy***

* ***Numpy is an advanced  library***
* ***Numpy ---Numerical Python***
* ***Numpy is to perform mathematical and statistical operations***
* ***The values are represented in the form of rows and columns***


* ***Advantages of Numpy when compared to lists***
    * ***It takes less time ***
    * ***performance will be high***
    * ***Occupies less memory***

In [1]:
import numpy as np

In [5]:
### creating an array using numpy
a = np.array([1,2,3,4])
a.size

4

In [6]:
### creating an array in particular range
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a = np.arange(1,11)
type(a)

numpy.ndarray

In [8]:
### checking the number of elements
a.size

10

In [10]:
a + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
a - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
a2 =np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
a2.size

8

In [18]:
np.arange?

In [19]:
a2 =np.array([[1,2,3,4],[5,6,7,8]],dtype=complex)
a2

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [20]:
a2.dtype

dtype('complex128')

In [21]:
a.dtype

dtype('int32')

In [24]:
a1 = np.arange(2,7) + np.arange(4,9)
a1

array([ 6,  8, 10, 12, 14])

In [25]:
### comparison of two arrays
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[4,5,6,7],[9,8,7,3]])

In [26]:
a > b

array([[False, False, False, False],
       [False, False, False,  True]])

In [27]:
a < b

array([[ True,  True,  True,  True],
       [ True,  True, False, False]])

In [28]:
a == b

array([[False, False, False, False],
       [False, False,  True, False]])

In [29]:
a // b

array([[0, 0, 0, 0],
       [0, 0, 1, 2]], dtype=int32)

In [30]:
a * b

array([[ 4, 10, 18, 28],
       [45, 48, 49, 24]])

In [31]:
a ** b

array([[      1,      32,     729,   16384],
       [1953125, 1679616,  823543,     512]], dtype=int32)

In [32]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [35]:
np.ones([5,5],dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.zeros([3,3],dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
a [0]

array([1, 2, 3, 4])

In [39]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
a[0:1]

array([[1, 2, 3, 4]])

In [43]:
a[0:1,1:2]### a[starting row:ending row,starting column ,ending coumn]

array([[2]])

In [46]:
a[:,1:3]

array([[2, 3],
       [6, 7]])

In [47]:
a[0][1]

2

In [49]:
a[:1,1:]

array([[2, 3, 4]])

In [55]:
a[1:,:3]

array([[5, 6, 7]])

In [51]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
a[:,:2]

array([[1, 2],
       [5, 6]])

In [56]:
a.shape

(2, 4)

In [57]:
a.ndim

2

In [58]:
a.nbytes

32

In [59]:
a.itemsize

4

In [61]:
b = np.arange(3,9)
b

array([3, 4, 5, 6, 7, 8])

In [63]:
b = np.arange(3,9)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [65]:
b.reshape(3,2)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [66]:
b.reshape(2,3)

array([[3, 4, 5],
       [6, 7, 8]])

In [67]:
min(b)

3

In [68]:
max(b)

8

In [69]:
np.std(b)

1.707825127659933

In [70]:
np.mean(b)

5.5

In [71]:
np.sum(b)

33

In [72]:
np.var(b)

2.9166666666666665

In [75]:
np.cumsum(b)

array([ 3,  7, 12, 18, 25, 33], dtype=int32)

In [77]:
np.argmin(b)

0

In [78]:
np.argmax(b)

5

In [81]:
b.transpose()

array([3, 4, 5, 6, 7, 8])

In [91]:
### binary to decimal
def binarytodecimal(a):
    a = int(input("enter a : "))
    d=0
    i=0
    while a!=0:
        binary = a % 10
        b = d + binary*(2**i) 
        a = a //10
        i = i+1
    print(b)
binarytodecimal(a)

enter a : 10
2


In [1]:
def decimaltobinary(n):
    if n>1:
        decimaltobinary(n//2)
    print(n%2,end=" ")
n = int(input("enter any decimal number: "))
decimaltobinary(n)

enter any decimal number: 10
1 0 1 0 